import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { v4 as uuidv4 } from 'uuid'
import type { Schema, Table, Column, Relation, ColumnType, SQLDialect } from '../types'

const DEFAULT_COLORS = [
  '#3ECF8E', '#3B82F6', '#8B5CF6', '#F59E0B',
  '#EF4444', '#06B6D4', '#EC4899', '#10B981'
]

export const useSchemaStore = defineStore('schema', () => {
  const schema = ref<Schema>({
    id: uuidv4(),
    name: 'Untitled Schema',
    tables: [],
    relations: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  })

  const selectedTableId = ref<string | null>(null)
  const selectedRelationId = ref<string | null>(null)
  const editingTableId = ref<string | null>(null)

  const selectedTable = computed(() =>
    schema.value.tables.find(t => t.id === selectedTableId.value) ?? null
  )

  function createTable(position = { x: 100, y: 100 }) {
    const colorIndex = schema.value.tables.length % DEFAULT_COLORS.length
    const table: Table = {
      id: uuidv4(),
      name: `table_${schema.value.tables.length + 1}`,
      comment: '',
      color: DEFAULT_COLORS[colorIndex],
      position,
      columns: [
        {
          id: uuidv4(),
          name: 'id',
          type: 'UUID',
          nullable: false,
          primaryKey: true,
          unique: true,
          defaultValue: 'gen_random_uuid()',
          comment: '',
        }
      ],
    }
    schema.value.tables.push(table)
    schema.value.updatedAt = new Date().toISOString()
    selectedTableId.value = table.id
    editingTableId.value = table.id
    return table
  }

  function updateTable(tableId: string, updates: Partial<Table>) {
    const table = schema.value.tables.find(t => t.id === tableId)
    if (table) {
      Object.assign(table, updates)
      schema.value.updatedAt = new Date().toISOString()
    }
  }

  function deleteTable(tableId: string) {
    schema.value.tables = schema.value.tables.filter(t => t.id !== tableId)
    schema.value.relations = schema.value.relations.filter(
      r => r.sourceTableId !== tableId && r.targetTableId !== tableId
    )
    if (selectedTableId.value === tableId) selectedTableId.value = null
    if (editingTableId.value === tableId) editingTableId.value = null
    schema.value.updatedAt = new Date().toISOString()
  }

  function addColumn(tableId: string) {
    const table = schema.value.tables.find(t => t.id === tableId)
    if (!table) return
    const col: Column = {
      id: uuidv4(),
      name: `column_${table.columns.length + 1}`,
      type: 'VARCHAR',
      nullable: true,
      primaryKey: false,
      unique: false,
      defaultValue: '',
      comment: '',
    }
    table.columns.push(col)
    schema.value.updatedAt = new Date().toISOString()
    return col
  }

  function updateColumn(tableId: string, columnId: string, updates: Partial<Column>) {
    const table = schema.value.tables.find(t => t.id === tableId)
    const col = table?.columns.find(c => c.id === columnId)
    if (col) {
      Object.assign(col, updates)
      schema.value.updatedAt = new Date().toISOString()
    }
  }

  function deleteColumn(tableId: string, columnId: string) {
    const table = schema.value.tables.find(t => t.id === tableId)
    if (table) {
      table.columns = table.columns.filter(c => c.id !== columnId)
      schema.value.updatedAt = new Date().toISOString()
    }
  }

  function addRelation(relation: Omit<Relation, 'id'>) {
    const rel: Relation = { id: uuidv4(), ...relation }
    schema.value.relations.push(rel)
    schema.value.updatedAt = new Date().toISOString()
    return rel
  }

  function deleteRelation(relationId: string) {
    schema.value.relations = schema.value.relations.filter(r => r.id !== relationId)
    schema.value.updatedAt = new Date().toISOString()
  }

  function updateTablePosition(tableId: string, position: { x: number; y: number }) {
    const table = schema.value.tables.find(t => t.id === tableId)
    if (table) table.position = position
  }

  function exportSQL(dialect: SQLDialect = 'postgresql'): string {
    const lines: string[] = []
    lines.push(`-- Generated by DB Modeler`)
    lines.push(`-- Dialect: ${dialect}`)
    lines.push(`-- ${new Date().toISOString()}`)
    lines.push('')

    for (const table of schema.value.tables) {
      lines.push(`CREATE TABLE ${table.name} (`)
      const colDefs: string[] = []

      for (const col of table.columns) {
        let def = `  ${col.name} ${col.type}`
        if (col.primaryKey) def += ' PRIMARY KEY'
        if (!col.nullable && !col.primaryKey) def += ' NOT NULL'
        if (col.unique && !col.primaryKey) def += ' UNIQUE'
        if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`
        colDefs.push(def)
      }

      // FK constraints
      for (const rel of schema.value.relations) {
        if (rel.sourceTableId === table.id) {
          const targetTable = schema.value.tables.find(t => t.id === rel.targetTableId)
          const srcCol = table.columns.find(c => c.id === rel.sourceColumnId)
          const tgtCol = targetTable?.columns.find(c => c.id === rel.targetColumnId)
          if (targetTable && srcCol && tgtCol) {
            colDefs.push(`  FOREIGN KEY (${srcCol.name}) REFERENCES ${targetTable.name}(${tgtCol.name})`)
          }
        }
      }

      lines.push(colDefs.join(',\n'))
      lines.push(');')
      lines.push('')
    }

    return lines.join('\n')
  }

  function saveToFile() {
    const json = JSON.stringify(schema.value, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${schema.value.name}.dbm.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  function loadFromJSON(json: Schema) {
    schema.value = json
  }

  return {
    schema,
    selectedTableId,
    selectedRelationId,
    editingTableId,
    selectedTable,
    createTable,
    updateTable,
    deleteTable,
    addColumn,
    updateColumn,
    deleteColumn,
    addRelation,
    deleteRelation,
    updateTablePosition,
    exportSQL,
    saveToFile,
    loadFromJSON,
  }
})
